name 'dkdeploy-core'
maintainer 'dkd Internet Service GmbH'
license 'MIT'
description 'Project cookbook'
version '1.0.0'

depends 'mysql', '~> 6.0'
depends 'mysql2_chef_gem', '~> 1.0'
depends 'database', '~> 4.0'
depends 'apt', '~> 2.9'
