sudo: required
language: ruby
services:
  - docker
cache: bundler
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

before_install:
  # Set file permission for local ssh private key
  - chmod 600 config/docker/ssh/vagrant
  - docker-compose up -d
  - gem install bundler --no-document

script:
  - bundle exec rubocop
  - bundle exec cucumber
